using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TypedScripts.Arguments;
using TypedScripts.Common;
using TypedScripts.Common.Exceptions;
using TypedScripts.Scripts.Exceptions;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TypedScripts.Scripts;

public class Script
{
    /// <summary>
    /// Array of arguments this script takes in.
    /// </summary>
    public ScriptArgument[] Arguments { get; } 

    /// <summary>
    /// This scripts C# object identifier.
    /// e.g. When set to <c>MyScript</c> then codegen will generate <c>public class MyScript ...</c> .
    /// </summary>
    public SafeIdentifier Identifier { get; }

    /// <summary>
    /// The file name of the source-generated script. 
    /// </summary>
    public string FileName => Identifier.Value + "g.cs";
    
    /// <summary>
    /// The shell this script must be executed with. 
    /// </summary>
    public Interpreter[] Interpreters { get; }
    
    /// <summary>
    /// The scripts generated syntax.
    /// </summary>
    public CompilationUnitSyntax Syntax { get; }

    private Script(
        SafeIdentifier identifier, 
        Interpreter[] interpreters, 
        ScriptArgument[] arguments, 
        CompilationUnitSyntax syntax)
    {
        Identifier = identifier;
        Arguments = arguments;
        Interpreters = interpreters;
        Syntax = syntax;
    }

    /// <summary>
    /// Factory method to create a new C# script object.
    /// </summary>
    /// <exception cref="InvalidIdentifierException">Thrown if the script identifier is invalid.</exception>
    /// <exception cref="NoInterpreterAvailableException">Thrown if no supported interpreters are available.</exception>
    /// <exception cref="InvalidScriptSyntaxException">Thrown if the generated syntax is invalid.</exception>
    public static Script Create(ScriptOptions options)
    {
        var arguments = options.Arguments.ToArray();
        var identifier = options.Identifier ?? new SafeIdentifier(GetFileNameIdentifier(options.FilePath));
        var interpreters = GetInterpreterPreferences(options.Interpreters, options.FilePath);
        var syntax = BuildSyntax(identifier, interpreters, arguments, options.Body);
        ValidateScriptSyntax(syntax);
        return new Script(identifier, interpreters, arguments, syntax);
    }

    private static string? GetFileNameIdentifier(string? filePath)
    {
        var fileName = Path.GetFileNameWithoutExtension(filePath);
        if (string.IsNullOrWhiteSpace(fileName)) return null;

        // Split on any run of non-alphanumeric chars (-, _, ., space, …) and
        // upper-case the first letter of each segment to form a PascalCase identifier.
        // Existing inner casing is preserved (e.g. "myWeb-deploy" -> "MyWebDeploy").
        var pascalCase = string.Concat(Regex
            .Split(fileName, "[^A-Za-z0-9]+")
            .Where(word => word.Length > 0)
            .Select(word => char.ToUpperInvariant(word[0]) + word.Substring(1)));

        return pascalCase.Length == 0 ? null : pascalCase;
    }
    
    private static Interpreter[] GetInterpreterPreferences(List<Interpreter> interpreters, string? filePath)
    {
        if (interpreters.Any()) return interpreters.ToArray();
        var inferred = InferInterpreterFromExtension(filePath);
        return inferred is null 
            ? throw new NoInterpreterAvailableException()
            : [ inferred.Value ];
    }

    // Fallback to extension based interpreter determination if shebang was not specified 
    private static Interpreter? InferInterpreterFromExtension(string? filePath) =>
        Path.GetExtension(filePath) switch
        {
            ".sh" => Interpreter.Bash,
            ".bash" => Interpreter.Bash,
            
            _ => null
        };

    private static void ValidateScriptSyntax(CompilationUnitSyntax syntax)
    {
        var diagnostics = syntax
            .GetDiagnostics()
            .ToArray();

        // Report script diagnostics if syntax contains errors 
        if (diagnostics.Any(x => x.Severity == DiagnosticSeverity.Error))
        {
            throw new InvalidScriptSyntaxException(diagnostics);
        }
    }
    
    private static CompilationUnitSyntax BuildSyntax(
        SafeIdentifier identifier, Interpreter[] interpreters, ScriptArgument[] arguments, StringBuilder body)
    {
        // TODO complete implementation of this auto-generated template
        // Execute script locally/remote with explicit methods -
        // "builder style" execution
        // 1. first method for interpreter default value set to first script argument
        // 2. second method takes in actual args and executes against target 
        var template = $$""""""
                        // <auto-generated/>
                        #pragma warning disable
                        #nullable enable
                        
                        namespace TypedScripts.Scripts;
                        
                        public class {{identifier.Value}} 
                        {
                            private const string ScriptContent = """ 
                                                                 {{body}}
                                                                 """;
                        }
                        """""";

        return ParseCompilationUnit(template);
    }
    
    /// <summary>
    /// Returns this script generated C# object representation. 
    /// </summary>
    public override string ToString() => Syntax.ToFullString();
}