using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TypedScripts.Arguments;
using TypedScripts.Core;
using TypedScripts.Scripts.Exceptions;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TypedScripts.Scripts;

public class Script
{
    /// <summary>
    /// Array of arguments this script takes in.
    /// </summary>
    public ScriptArgument[] Arguments { get; } 

    /// <summary>
    /// This scripts C# object identifier.
    /// e.g. When set to <c>MyScript</c> then codegen will generate <c>public class MyScript ...</c> .
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// The file name of the code-gen script. 
    /// </summary>
    public string FileName => Name + "g.cs";
    
    /// <summary>
    /// The shell this script must be executed with. 
    /// </summary>
    public Shell Shell { get; }
    
    /// <summary>
    /// The scripts generated syntax.
    /// </summary>
    public CompilationUnitSyntax Syntax { get; }

    public Script(string name, string scriptContent, Shell shell, ScriptArgument[] arguments)
    {
        if (!SyntaxFacts.IsValidIdentifier(name))
        {
            throw new InvalidScriptIdentifierException(name);
        }
        
        Arguments = arguments;
        Name = name;
        Shell = shell;
        Syntax = Build(name: name, scriptContent: scriptContent, arguments: arguments);
    }

    public override string ToString() => Syntax.ToFullString();

    private static CompilationUnitSyntax Build(string name, string scriptContent, ScriptArgument[] arguments)
    {
        // TODO complete implementation of this auto-generated template
        // For more details the infrastructure layout must be "completed"
        var template = $$""""""
                        // <auto-generated/>
                        #pragma warning disable
                        #nullable enable
                        
                        namespace TypedScripts.Scripts;
                        
                        public class {{name}} 
                        {
                            private const string ScriptContent = """ 
                                                                 {{scriptContent}}
                                                                 """;
                        }
                        """""";

        var unit = ParseCompilationUnit(template);

        var diagnostics = unit
            .GetDiagnostics()
            .ToArray();

        // Report compilation 
        return diagnostics.Any(x => x.Severity == DiagnosticSeverity.Error) 
            ? throw new InvalidScriptSyntaxException(diagnostics) 
            : unit;
    }
}